name: Lint
on: [push, pull_request]
jobs:
  lint:
    strategy:
      matrix:
        go:
          - stable
          - oldstable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
